# Generated by Django 5.1.4 on 2024-12-08 04:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('puntos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('nroci', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Disiplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignado', models.DateField(default=datetime.date.today)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.estudiante')),
                ('tipo_falta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.tipofalta')),
            ],
        ),
    ]
